# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site

lantitle: 张.态度友好又和善.公私分明不计较.24K纯吐槽.叕被人跟踪骚扰.害怕打车朋友多.敏 's Blog
subtitle: 本人只吐槽不骂人，善良成天被骚扰。工作负责，不爱计较。BUG少（当面提过来的BUG就是骚扰）
author: 张.态度友好又和善.公私分明不计较.24K纯吐槽.叕被人跟踪骚扰.害怕打车朋友多.敏
guage:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://azliya.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Azliya | Azliya's Blog
header-img: img/home-bg.jpg
email: zhangmin093@foxmail.com
description: ""
keyword: ""


# SNS settings
# RSS: false
# weibo_username:     Demonbane
# zhihu_username:     Demonbane
github_username:    Azliya
# twitter_username:   Demonbane_x
# facebook_username:  demonbane.cn
# linkedin_username:  kaijun-chen-42089354

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
# disqus_username: hexo-theme-huxblog

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: ./img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
# friends: [
    # {
    #     title: "Kaijun's Blog",
    #     href: "http://blog.kaijun.rocks"
    # },{
    #     title: "Hux Blog",
    #     href: "http://huangxuan.me"
    # },{
    #     title: "Foo",
    #     href: "#"
    # },{
    #     title: "Bar",
    #     href: "#"
    # },{
    #     title: "Example Friends",
    #     href: "#"
    # },{
    #     title: "It helps SEO",
    #     href: "#"
    # }
# ]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: i_dont_wanna_use_default_archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Azliya/azliya.github.io
  branch: master
